### ISSUE TITLE
Support for Behat CLI syntax

### ISSUE THREAD

**Issue by pamil** [FriendsOfBehat/ExcludeSpecificationsExtension#5]
`features/abc/` - skips a directory
`features/abc/def.feature` - skips a feature
`feature/abc/def.feature:12` - skips a scenario from a feature
`feature/abc/def.feature:12-28` - skips scenarios defined in given lines from a feature

**Comment by Zales0123** [comment]
My first idea was to propose this configuration:

``` yml
FriendsOfBehat\SkipExtension:
    features:
        - feature/feature_to_skip.feature
    scenarios:
        - name of scenario to skip
    tags:
        - tag to be skipped
```

However, Behat CLI syntax would be more natural... What about merging this two ideas together? Just loudly thinking 😄
